### ISSUE TITLE
We appear to not have a term for "fat cell"

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#110]
I'm failing to find a term for the cells comprising the fat body FBbt:00005066. No fat cell, fat body cell, adipocyte, or adipose cell. I think we should pick a term, and make the other terms exact synonyms.

Context: I'm curating FBrf0228918, which states that the GAL4 drive Scer\GAL4[SPARC-MI00329-GAL4] drives expression in adipocytes. I suspect there's some upstream reference to be cited in a definition, but I'm not sure what that might be. The Atlas of Drosophila Development (Volker Hartenstein) mentions the fat body being comprised of cells. FBrf0158816 might be a good starting place.

**Comment by temjones** [comment]
Hi Sian,
I actually noticed this myself recently! Definitely going on the to-do list.
T

**Comment by temjones** [comment]
I have added a generic "fat cell" term. It may also be desirable to add more granular detail with additional terms for fat cells at different stages, but I have not gone into this level of detail right now due to time constraints, and this would not appear to be high priority atm. Definitely open to adding these in future.

**Comment by SianGramates** [comment]
I think the generic "fat cell" is sufficient to our needs.
