### ISSUE TITLE
missing superclasses?

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#1123]
New dashboard report is out:
http://dashboard.obofoundry.org/dashboard/fbbt/robot_report.html

It includes this: 

Rule | Number of errors
-- | --
missing_superclass | 3022

Unfortunately the TSV download is clipped at 200 so doesn't show these.

Can you run a ROBOT report locally so we can see if these are genuine and if so, decide what to do with them?

**Comment by dosumis** [comment]
Looks like SPARQL for report is not here: https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/tree/master/src/sparql

You might want to consider updating ODK to get it & any others you may be missing.

**Comment by Clare72** [comment]
ODK is up to date - no changes from running `sh run.sh make update_repo`
what is it that is missing?

**Comment by dosumis** [comment]
Couldn't work out what's generating the missing superclass report.  @matentzn - could you point us to the the relevant sparql?

**Comment by matentzn** [comment]
You can find all queries here: http://robot.obolibrary.org/report_queries/

Missing superclass is really not a useful test, as there are necessarily some classes that don't have a superclass (the root terms). I have [made a proposal](https://github.com/ontodev/robot/issues/843) on the ROBOT repo to be able to flag exceptions to tests.

**Comment by dosumis** [comment]
Thanks.  Had forgotten they are now built-in.  Test may be useful in this case, given apparently large number of classes affected.

**Comment by Clare72** [comment]
The two reports with missing_superclass that are generated during the release are 'fbbt-edit-release.owl-obo-report.tsv' and 'fbbt.owl-obo-report.tsv'

'fbbt-edit-release.owl-obo-report.tsv' has 3076 results for missing_superclass, which includes terms that have a superclass in the 'Equivalent To' field, but not in the 'SubClassOf' field in fbbt-edit.obo.

'fbbt.owl-obo-report.tsv' has 2 results for missing_superclass - 'anatomical entity' (root term) and 'cellular component' (GO term that also sits at root level).

Perhaps the dashboard is making/using the 'fbbt-edit-release.owl-obo-report.tsv' report instead of the 'fbbt.owl-obo-report.tsv' report?

**Comment by matentzn** [comment]
Dont worry about missing superclasses too much, there are some big dashboard changes coming to do this properly

**Comment by Clare72** [comment]
closing this issue as I don't think any changes to FBbt are required
