### ISSUE TITLE
Improve xrefs

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-anatomy-developmental-ontology#1207]
FBbt has xrefs to several other resources including [DoOR](http://neuro.uni-konstanz.de/DoOR/default.html) and [larvalbrain](http://www.larvalbrain.org/).
We also have xrefs to other ontologies, including GO and CL.
Consider how to improve these with sssom:
https://github.com/mapping-commons/SSSOM/blob/master/SSSOM.md

**Comment by gouttegd** [comment]
Since we are already using SSSOM for the mappings with CL and Uberon, we can easily use it also for the other resources.

For the “larvalbrain“ ref, this could entirely replace the `components/larvalbrain_compartments.owl` and `components/larvalbrain_fascicles.owl` components, which contain only the cross-references to the `larvalbrain` resource.
