### ISSUE TITLE
intermediate zone of lymph gland primary lobe (and) intermediate progenitor

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#1401]
I'm kind of unsure about this, as it doesn't look like a new issue.

intermediate zone of lymph gland primary lobe 
Papers call this 'intermediate zone'; synonym is IZ.
It's found at the margins of the cortical and medullary zones of the lymph gland primary lobe, and contain what papers call 'intermediate progenitors' (which sounds much too generic to me). It's not clear to me if intermediate progenitor is a subdivision of prohemocyte or possibly developmentally between lymph gland stem cell and prohemocyte.

Reviewed in PMID: 30733377

intermediate progenitor first described in PMID: 20707995
intermediate zone described (includes molecular markers) in PMID: 34918741, PMID: 34713801

**Comment by Clare72** [comment]
Looking at these papers, it seems that 'intermediate progenitor' is considered to be a distinct cell type (reminiscent of enteroblasts in the gut), that is neither a prohemocyte, nor a hemocyte, so I think we should have a term for this (and the intermediate zone).

I also noticed that 'prohemocyte' is currently part of an embryonic structure, which is odd, since it is not defined to be embryonic in the definition and existing references include the larva, so I will remove this assertion.
