### ISSUE TITLE
FBbt_00001888 has typo in def ref '['

### ISSUE THREAD

**Issue by Robbie1977** [FlyBase/drosophila-anatomy-developmental-ontology#151]
```obo_definition_citation:{"definition":"Columnar cell of the middle midgut, with short microvilli and deep infolding of the basement membrane forming a basal labyrinth. In the anterior region of the middle midgut, these cells alternate with copper cells. Their diameter increases from anterior to posterior.","oboXrefs":[{"database":"[FlyBase","id":"FBrf0100557","description":null,"url":null},{"database":"FlyBase","id":"FBrf0064792","description":null,"url":null}]}```

Spot the random: ```"database":"[FlyBase"```
which should be: ```"database":"FlyBase"```

**Comment by temjones** [comment]
YIKES. Well spotted. There are 3 other instances of this too. I’ll correct all of these.

**Comment by dosumis** [comment]
Thought we had a test for valid DB names in dbxrefs running on Jenkins using my old perl libs.  Only => warnings so may have been ignored.

**Comment by temjones** [comment]
I thought so too, from memory I think they’re regexps so maybe this is getting through somehow? But failures to dbxref tests should throw up an warning that wouldn’t be missed, we generally examine all warnings for dbxrefs in the SOP as far as I know. Will check what's going on there.

**Comment by temjones** [comment]
I have corrected these in FBbt. Not sure why the checks aren't picking it up - this is checked in chado_load_checks.pl and I don't know enough perl to troubleshoot. 

The chado_load_checks.out file is generated with each Jenkins build and is always checked in preparing an FBbt release so dbxref formatting errors won't be missed, but of course that's only if the script actually flags them up. Would be good to fix the script so that it picks this up.

**Comment by Robbie1977** [comment]
@dosumis did you amend the script?
