### ISSUE TITLE
Missing FBbt --> CL mappings

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#1583]
## Background

UberGraph has CL, FBbt and the CL-FBbt bridge.

Versions loaded to UberGraph:
http://purl.obolibrary.org/obo/uberon/bridge/cl-bridge-to-fbbt/2022-09-30/uberon/bridge/cl-bridge-to-fbbt.owl
http://purl.obolibrary.org/obo/fbbt/fbbt-base.owl,http://purl.obolibrary.org/obo/fbbt/releases/2022-12-01/fbbt-base.owl
h

Some examples of useful bridging in UberGraph resulting from this: https://api.triplydb.com/s/WnK-lbvyS

General question: is this now out of date?  Should we be pointing UberGraph to a release file on this repo instead?

## Evidence for missing mappings
There are quite a number of terms in CL that are obviously superclasses of FBbt terms but which have no subclasses in the combined CL & FBbt in UberGraph (as judged by IC = 100 indicating leaf node status:  https://api.triplydb.com/s/J3OcIK_ge), e.g. 

* 'imaginal disc cell' should subsume ['imaginal disc epithelial cell'](https://www.ebi.ac.uk/ols/ontologies/fbbt/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBbt_00007108&lang=en&viewMode=PreferredRoots&siblings=false)
* 'Kenyon cell' - has many subClasses in FBbt

From spot checking it looks like these are missing from the mappings file here (based on recent PRs I'm guessing that this is where the mappings live):

https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/blob/master/src/ontology/mappings.tsv

**Comment by gouttegd** [comment]
> General question: is this now out of date? Should we be pointing UberGraph to a release file on this repo instead?

No to both questions. The bridge generation logic is in the Uberon repository (the `make-bridge-ontologies-from-xrefs.pl` script), so this is still where the bridge files live and Ubergraph is right to get them from there. FBbt only provides the SSSOM file.

Ultimately I hope to overhaul the bridge generation process to produce the bridges straight from the SSSOM file (which could allow FBbt to generate its own bridge file instead of being dependent on Uberon for that), but the available SSSOM tooling is not up to the task for now.

(Strictly speaking, the bridges that are part of the 2022-09-30 Uberon release are _slightly_ out-of-date, but that is simply because another Uberon release happened on 2022-12-13; I don’t know how often is Ubergraph rebuilt, but the last build was probably before that date. I expect the next Ubergraph build will automatically use the latest Uberon.)

> From spot checking it looks like these are missing from the mappings file here

That’s very likely. When working on those mappings I have mainly focused for now on removing or fixing _existing_ mappings that were problematic for one reason or another, and not so much on adding _new_ mappings that might be missing.

I’ll add missing mappings as needed, but before I add too much of them I’d very much like to come up with a way to easily and efficiently detect whether the new mappings are going to cause downstream issues (without having to wait for a new Ubergraph release to detect any problem), as described in INCATools/ontology-development-kit#765.

> based on recent PRs I'm guessing that this is where the mappings live

Indeed.

**Comment by dosumis** [comment]
A few missing mappings to add based on matching names:  

https://api.triplydb.com/s/1vU8Ua6aM

x | y | xlab | z
-- | -- | -- | --
http://purl.obolibrary.org/obo/CL_0000196 | 100 | flight muscle cell | http://purl.obolibrary.org/obo/FBbt_00003360
http://purl.obolibrary.org/obo/CL_0000380 | 100 | thecogen cell | http://purl.obolibrary.org/obo/FBbt_00005173
http://purl.obolibrary.org/obo/CL_0000673 | 100 | Kenyon cell | http://purl.obolibrary.org/obo/FBbt_00003686
http://purl.obolibrary.org/obo/CL_0000729 | 100 | tertiary pigment cell | http://purl.obolibrary.org/obo/FBbt_00004233
http://purl.obolibrary.org/obo/CL_0000534 | 100 | primary interneuron | http://purl.obolibrary.org/obo/FBbt_00052517
http://purl.obolibrary.org/obo/CL_0000727 | 100 | primary pigment cell | http://purl.obolibrary.org/obo/FBbt_00004231
http://purl.obolibrary.org/obo/CL_0000728 | 100 | secondary pigment cell | http://purl.obolibrary.org/obo/FBbt_00004232
http://purl.obolibrary.org/obo/CL_0000482 | 100 | juvenile hormone secreting cell | http://purl.obolibrary.org/obo/FBbt_00058020


Looks like CL terms lack definitions, so either a generalised definition should be added to CL or the term dropped from CL.    I think we should probably take the former strategy for all except the primary, secondary and tertiary pigment cells, which I suspect might be highly taxonomically specific, and possibly for "primary interneuron".

Mapping also needed for 
* 'imaginal disc cell' -  should subsume ['imaginal disc epithelial cell'](https://www.ebi.ac.uk/ols/ontologies/fbbt/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBbt_00007108&lang=en&viewMode=PreferredRoots&siblings=false)


Happy to call this ticket complete when all these mappings have been addressed.  I suspect we will find more that don't match exactly on label by reviewing IC=100 terms 
in CL.  I'll make a separate ticket for that.

**Comment by gouttegd** [comment]
> Looks like CL terms lack definitions, so either a generalised definition should be added to CL or the term dropped from CL. I think we should probably take the former strategy for all except the primary, secondary and tertiary pigment cells, which I suspect might be highly taxonomically specific

I agree for those three terms. The parent term (_visual pigment cell (sensu Nematoda and Protostomia)_) is already mapped to the parent term in FBbt (_pigment cell_), so I think CL does not need the primary/secondary/tertiary subclasses – I’ll propose them for obsoletion in CL.

> possibly for "primary interneuron"

Not sure about this one (and the associated “primary neuron”, “primary sensory neuron”, “primary motor neuron”).

In FBbt, “primary neuron” is clearly defined as a neuron born during embryonic neurogenesis (as opposed to a neuron born during larval neurogenesis). This concept of “two-stages neurogenesis” is not specific to flies – from a cursory look, it seems to also happen at least in zebrafish and frogs. So having “primary neuron” in CL _with that meaning_ would be justified.

But because neither “primary neuron” nor any of its subclasses have a definition in CL, it’s unclear what their intended meaning was, or what it should be. I note that in Uberon, “neurectoderm” is a subclass of `has_parts some "primary neuron"`, which suggests that “primary neuron” was _not_ intended to be applicable only to species with two-stages neurogenesis.

We should clarify the intended meaning of “primary neuron” (and the “primary interneuron“, “primary motor neuron“, “primary sensory neuron“ subclasses) in CL (which includes deciding whether those terms are actually needed in CL or not) before mapping them, or not, to the corresponding FBbt terms.

**Comment by gouttegd** [comment]
The missing mappings flagged in this ticket have been added where necessary. Closing here.
