### ISSUE TITLE
NTR: 'body without head' FCA sample

### ISSUE THREAD

**Issue by ANiknejad** [FlyBase/drosophila-anatomy-developmental-ontology#1605]
Hello FlyBase Team,

To report single-cell transcriptomics, we (at bgee.org) are also annotating the anatomical structures, tissues, the single-cell librairies are generated from.

https://flycellatlas.org/body/

For tissue='body without head', there is currently none available class in DAO, as far as I can see.

Would it be possible to add a class to define this (adult) organism without head?

[Term]
id: FBbt:xxxxxxxx
name: body without head (Drosophila)
def: "The part of the drosophila organism that encompass the whole body except the head." [https://flycellatlas.org/body/]
synonym: "body" RELATED []
is_a: UBERON:0000475 ! organism subdivision

Thank you in advance for your help.

Cheers,

Anne

**Comment by Clare72** [comment]
I think a better term label would be something like 'postcephalic region'
see [FBrf0055836](http://dev.biologists.org/content/115/4/1017.long) and [FBrf0220416](https://www.sciencedirect.com/science/article/pii/S146780391200076X)
Since FBbt is supposed to represent wild-type anatomy, rather than samples, we generally do not make terms to represent arbitrary combinations of body parts (using 'with', 'without' etc.), but I think it is justified in this case.

NB - [FBrf0055166](https://www.sciencedirect.com/science/article/pii/016895259190327M) explicitly does not include gnathal segments as 'cephalic', but I think this is an exception.

**Comment by ANiknejad** [comment]
Thank you for your comment, Clare. Yes, 'postcephalic region' sounds much better! I also agree with you about representing the wild-type anatomy in ontologies, but at the end by using ontologies, we also aim to have a common language to make data reusable and having ontological terms to describe samples helps in this purpose.
