### ISSUE TITLE
New Term Request: mlSEZt

### ISSUE THREAD

**Issue by admclachlan** [FlyBase/drosophila-anatomy-developmental-ontology#1636]
For new term requests, please provide the following information:

## Preferred term label

mediolateral SEZ gustatory tract neuron (from https://www.sciencedirect.com/science/article/pii/S0896627317309790?via%3Dihub - maybe needs a more specific name?)

## Synonyms

mlSEZt

## Textual definition

FBrf0255549

second order bitter neurons in the ml sez tract.

## Suggested parent term

gustatory projection neuron or subclass of.

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by gouttegd** [comment]
I note that we already have [bitter gustatory local interneuron](http://purl.obolibrary.org/obo/FBbt_00048033) (bGLN), described in FBrf0238406, but they are clearly _not_ the same as the mlSEZt neurons described here:

* There is only one bGLN per hemisphere, while there are clearly more than one mlSEZt.
* Most importantly, the bGLN are located in the SEZ, while the mlSEZt receive synaptic input from the SEZ but their soma is the vicinity of the antennal lobes.
* In fact the bGLN could be one of the neurons the mlSEZt neurons receive input from, instead of (or in addition to) the bitter-sensing neurons themselves (that’s a possibility acknowledged by the authors: “We will therefore refer to mlSEZt neurons as second-­order bitter neurons, although it is formally possible that they are downstream bitter neurons that are not directly connected to bitter-­sensing cells”).

We also have [adult mediodorsal antennal lobe neuron 3](http://purl.obolibrary.org/obo/FBbt_00052189) (mAL3), whose description matches the description of the mlSEZt neurons. But the overlap between mAL3 and mlSEZt is unclear: not all mAL3 neurons may be mlSEZt, and mlSEZt may correspond to more than just mAL3.

**Comment by gouttegd** [comment]
As part of this ticket, we should also add the gustatory tracts and gustatory projection neurons described in Talay et al., 2017 (FBrf0237282), of which the bitter mlSEZt neurons described in Deere et al., 2023 (FBrf0255549) are a subset.

So I plan to add, from FBrf0237282:

* `medial supraesophageal gustatory tract` (mSEZt);
  * `posteroventral projection neuron of the medial supraesophageal gustatory tract`;
  * `anterodorsal projection neuron of the medial supraesophageal gustatory tract`;
* `mediolateral supraesophageal gustatory tract` (mlSEZt);
  * `projection neuron of the mediolateral supraesophageal gustatory tract`;
* `lateral supraesophageal gustatory tract` (lSEZt);
  * `antenno-mechanosensory center projection neuron of the lateral supraesophageal gustatory tract`;
  * `ventral nerve cord projection neuron of the lateral supraesophageal gustatory tract`;

and from FBrf0255549:

* `bitter projection neuron of the mediolateral supraesophageal gustatory tract`

(which is the term initially requested) as a subclass of `projection neuron of the mediolateral supraesophageal gustatory tract`.
