### ISSUE TITLE
New Term Request: wing/haltere motor neurons

### ISSUE THREAD

**Issue by admclachlan** [FlyBase/drosophila-anatomy-developmental-ontology#1638]
For new term requests, please provide the following information:

not sure if we need these, I could just curate these to subsets of haltere muscle motor neuron or wing motor neurons.

## Preferred term label

haltere Dorsal Ventral [Indirect Flight] Muscle (motor neuron)
posterior haltere axillary muscle i1 (motor neuron)

## Synonyms

hDVM (motor neuron)
hi1 (motor neuron)

## Textual definition

FBrf0243782
hDVM - as DVM, not sure if we want a wing and haltere specific term for these (there's also wDVM). Need the motor neuron for this paper.
hi1 - "he more posterior haltere axillary muscles (hI1, hI2, hIII1, hIII2, and hIII3"

## Suggested parent term

haltere muscle motor neuron

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by gouttegd** [comment]
Based on the descriptions and on figure 1A in FBrf0243782, I think that:

* hDVM (the pendant of the dorso-ventral indirect flight muscle for the haltere) is our [haltere muscle 77](http://purl.obolibrary.org/obo/FBbt_00058939);
* hB1 and hB2 (the haltere basalar muscles) are our [haltere muscle 78a](http://purl.obolibrary.org/obo/FBbt_00058941);
* hI1, hI2, hIII1, hIII2, and hIII3 (the haltere axillary muscles) are our [haltere muscle 78](http://purl.obolibrary.org/obo/FBbt_00058940).

But we don’t have any terms for the motor neurons for each of those muscles – we just have [haltere muscle motor neuron](http://purl.obolibrary.org/obo/FBbt_00051966).

So what we can at least do:

* add synonyms to our existing haltere muscle terms to reflect the nomenclature used in this paper;
* add a subclass of [haltere muscle motor neuron](http://purl.obolibrary.org/obo/FBbt_00051966) for all three of them (motor neuron of hDVM, motor neuron of haltere basalar muscle, motor neuron of haltere axillary muscle).

But I am reluctant to create more precise terms for the two basalar muscles (hB1, hB2) and the 5 axillary muscles (hI1, hI2, etc.), since they are not described in any details (same for their corresponding motor neurons).

@admclachlan Would a single `haltere basalar muscle motor neuron`, which would represent indiscriminately the motor neurons of both hB1 and hB2, be enough? Or do you need `hB1 motor neuron` and `hB2 motor neuron` as separate terms? Ditto for the hI1, hI2, etc.

Regarding the wing motor neurons, we can add a `dvm motor neuron` to represent the motor neurons of the wing dorsal ventral indirect flight muscle, which are currently not represented. The new term will be on par with the existing [dlm motor neuron](http://purl.obolibrary.org/obo/FBbt_00048112), which represents the motor neurons of the wing dorsal medial indirect flight muscle.

**Comment by admclachlan** [comment]
Thanks Damien, the less specific terms would be fine.
