### ISSUE TITLE
KeyError: 'BFO:0000141' while loading 2024-10-17 Release

### ISSUE THREAD

**Issue by Praniyendeev** [FlyBase/drosophila-anatomy-developmental-ontology#1933]
While trying to load the ontology using pronto from the file fbbt-full.obo from the latest release( 2024-10-17 ) throws a key error for the term BFO:0000141. 
The older versions of the file do contain the term id and definition, seems like its missing in this one.

**Comment by gouttegd** [comment]
> The older versions of the file do contain the term id and definition, seems like its missing in this one.

I believe it is also missing (along with several other BFO terms) from the 2024-08-08 and 2024-06-13 releases. The last release to include it was the 2024-04-25 one.

They are no longer present because RO stopped including them in their `-base` release (likely because they migrated to ODK 1.5).

We might need to explicitly import BFO -- or alternatively, consider dropping CARO (AFAIK all the dangling BFO terms, including BFO:0000141, are referenced from CARO).

**Comment by Clare72** [comment]
Probably easiest to import BFO - not sure what we might break by dropping the CARO classifications.

In the meantime @Praniyendeev, if it suits your use case you can try the fbbt-simple.obo file (which does not contain imported classes).
You could also try using the sqlite version of fbbt via [oak](https://incatools.github.io/ontology-access-kit/index.html) - use `"sqlite:obo:fbbt"` when following the examples. I am not 100% sure which artefact of fbbt it is based on, as it is not something that we (fbbt maintainers) produce here, but I would guess that it is based on fbbt.owl. It does contain the relationships to external terms if that is something you need.
