### ISSUE TITLE
Expand and fix overlapping definitions of larval motor neurons and new term requests for motor neurons

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#281]
FBrf0234013 describes in detail many motor neurons in the larvae, several of which persist to adults. Many of these appear to be duplicated in the ontology.

- [x] A1-7 VO4/5 motor neuron AND VO4/5 motor neuron (fasiculates with intersegmental nerve branch ISNd of A1-7)
- [x] A1-7 VO4-6 motor neuron AND VO4-6 motor neuron (fasiculates with intersegmental nerve branch ISNd of A1-7)
- [x] A1-7 ventral motor neuron AND RP5 motor neuron (fasiculates with intersegmental nerve branch ISNb of A1-7 AND intersegmental nerve branch ISNd of A1-7)
- [x] A1-7 ventral VUM motor neuron AND ventral VUM motor neuron (fasiculates with intersegmental nerve branch ISNb of A1-7 AND intersegmental nerve branch ISNd of A1-7)
- [x] A1-7 VL3/4 motor neuron is OK (fasiculates with intersegmental nerve branch ISNb of A1-7)
- [x] A1-7 VO3 motor neuron AND VO3 motor neuron (fasiculates with intersegmental nerve branch ISNb of A1-7)
- [x] A1-7 VO2 motor neuron is OK (fasiculates with intersegmental nerve branch ISNb of A1-7)
- [x] A1-7 VO1 motor neuron is OK (fasiculates with intersegmental nerve branch ISNb of A1-7)
- [x] A1-7 VL2 motor neuron needs definition expanded (fasiculates with intersegmental nerve branch ISNb of A1-7)
- [x] A1-7 DO5 motor neuron is OK (fasiculates with intersegmental nerve of A1-7)
- [x] A1-7 dorsal motor neuron is OK (fasiculates with intersegmental nerve of A1-7)
- [x] A1-7 dorsal VUM motor neuron AND dorsal VUM motor neuron (fasiculates with intersegmental nerve of A1-7)
- [x] A1-7 DO4 motor neuron AND DO4 motor neuron (fasiculates with intersegmental nerve of A1-7)
- [x] A1-7 DO3 motor neuron AND DO3 motor neuron (fasiculates with intersegmental nerve of A1-7)
[Clare edit: this list made into check boxes]

Suggest using the parent term as that is what I''m curating to for FBrf0234013

New term needed for MN26-Ib (fasiculates with segmental nerve branch SNc of A1-7)
New term needed for MN12-Ib (fasiculates with segmental nerve branch SNc of A1-7)

Whole bunch of larval neurons that persist as adults need named as adult neurons (summarised Table 4).

**Comment by Clare72** [comment]
For VO4/5 and VO4-6, which are defined by the muscle they innervate, they are only present in A1-7, because VO4, 5 and 6 muscles are only found in A1-7. I have merged these terms and if a similar class is found in the thorax, a sister term, rather than a child term will be needed.

For other classes, it is difficult to find evidence that they are A1-7-specific. For some, it seems that they are also found in thoracic segments e.g. RP5 (FBrf0112030). Where this is the case, the parent and child terms are not equivalent, so I will not merge them.

I will try to make it clearer which are A1-7-specific or not as I look through the list. Most research seems to focus on abdominal neurons, but this does not exclude the possibility of T1-3 or A8 versions of these neurons existing.

**Comment by Clare72** [comment]
Fixing/Clarifying done - need to add details from Fbrf0234013
