### ISSUE TITLE
rename of adult female posterior abdominal ganglion neuron (not retained as synonym)

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#329]
I have some discomfort with this rename; partly because it looks like this term has been attached to curation for only two papers: phenotype to FBrf0222499 and expression to FBrf0225544. My discomfort is mainly centered around whether the two papers are referring to the same two neurons (the expression paper does not mention Ilp7). If they're the same, the old term should be retained as a synonym. If they're different, the expression paper appears to signal need for a new term, and that new term should be attached to the expression statements.

adult female posterior abdominal ganglion neuron ; FBbt:00110664 has changed name to adult post-embryonic ventral posterior ILP7 (female) neuron. The old name is not a synonym. (I note this has changed name again due to the ILP7/Ilp7 issue. I agree vehemently with not making the intermediate term a synonym; good call on that whole naming scheme.)

**Comment by Clare72** [comment]
The earlier term (in 2018-02-21 version of FBbt) was based on FBrf0222499 with no mention of FBrf0225544. I based my edits on this reference alone to address this ticket:
https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/issues/237

The old term name was ambiguous because there are two groups of female posterior abdominal ganglion neurons mentioned in this paper, one dorsal, one ventral. The old definition stated that that the term referred to the ventral cluster, so for me there was no ambiguity about what the term was referring to and I decided to clarify it (so that not everyone would have to read the reference to work out what it meant!)

Without reading FBrf0225544, I am not sure if the curator has used the term correctly or not, but I don't think it is my responsibility to check that terms like this are being used correctly.

Regarding synonym retention - I can add it as a "broad synonym" if you like, but as I said, I think the old name was ambiguous.

**Comment by SianGramates** [comment]
Broad synonym is good.

I've reviewed the relevant expression proforma; it's from the VFB curator before Alex. I could (and will) ask Alex to take a look at the curations and weigh in with an opinion as to whether they refer to the same neurons.
