### ISSUE TITLE
subesophageal ganglion serotonergic SE neuron rename; synonym not retained

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#334]
I'm not understanding what happened here (have been hunting for the original ticket). It looks like the definition and relationships, as well as the name, have changed. I'm not understanding why it's no longer a subesophageal ganglion neuron (is that not what SE is an abbreviation of?).

subesophageal ganglion serotonergic SE neuron ; FBbt:00100358 has changed name to serotonergic SE neuron. The old name is not a synonym.

**Comment by Clare72** [comment]
"subesophageal ganglion neuron" is currently logically defined as <neuron and ('part of' some 'subesophageal ganglion')>

The problem with using part_of here is that the entire neuron must be within the subesophageal ganglion for this part_of to be true. This problem exist for neurons all over the ontology. I have made myself an epic ticket - #280 to try to fix this (changing to has_soma_location instead of part_of), but it may take some time to sort out. The serotonergic SE neurons have their cell bodies in the subesophageal ganglion, but are not necessarily part_of it - so they do not qualify as subesophageal ganglion neurons under the current definition.

As for synonyms, I seem to have missed "serotonergic" out of all of them for the SE neurons - this was an oversight on my part and I will look through and fix them.

The ticket was #104 - I took the opportunity to look over all the existing terms as well as adding the new ones using FBrf0213697 and FBrf0234216.
