### ISSUE TITLE
optic lobe renamed; synonym not retained

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#335]
optic lobe ; FBbt:00003701 has changed name to adult optic lobe. The old name is not a synonym.

I can see what you're doing here. BUT, "optic lobe" is widely used in the literature. Revive as is_a parent for adult optic lobe and embryonic/larval optic lobe FBbt:00001930 ?

**Comment by Clare72** [comment]
Yes, I thought about doing this - the larval and adult terms are connected by develops_from, so wasn't sure if this was needed or what the definition would be (since larvae don't have eyes, I guess the larval optic lobe doesn't do much).

As with a lot of other terms, I was thinking about searches when making decisions about synonyms - "optic lobe" would pick up the adult and larval terms, as well as a bunch of other terms for parts of optic lobes and optic lobe neurons. Not too much trouble to add back as 'broad synonym', though.

If "optic lobe" were introduced as a superclass, would you still want it as a broad synonym for the adult class?
