### ISSUE TITLE
Improve definition of adult doublesex neuron

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#429]
Current definition is:

_Any neuron (FBbt:00005106) that is part of some adult (FBbt:00003004)._

Change to:

_Doublesex expressing neuron of the adult._

**Comment by Clare72** [comment]
This is a problem with the autogenerated definition.

This is the logical definition:
neuron and ('part of' some adult) and (expresses some doublesex)

@dosumis how do we get the expression into the autogenerated definition?

**Comment by dosumis** [comment]
I suspect this is because my Perl OBO parser is rejecting the FlyBase IRIs we use for this.  Fixing properly will involve editing Perl (or rewriting the autodef script in a different language - probably Scala if I do it).  In the meantime, you can fix this by writing a manual definition for this and similar terms.  (The autodef only gets added when the definition in the editor's' file  = "." )

**Comment by Clare72** [comment]
dsx neuron definition fixed - leaving this open as underlying issue (autogeneration of definitions) not fixed.

**Comment by Clare72** [comment]
Fixed by Nico's new autodefinition generation script.
