### ISSUE TITLE
New term/Synonym Essential Amino Acid Deficiency Sensing neurons

### ISSUE THREAD

**Issue by ah963** [FlyBase/drosophila-anatomy-developmental-ontology#453]
FBrf0223961 describes Essential Amino Acid Deficiency Sensing (EAAD sensing) neurons. Based on the anatomical description - project to mushroom body and SOG (fig5) - these may be the existing neurons, larval dopaminergic DL1-6 neuron. In which case a synonym would be sufficient.

**Comment by Clare72** [comment]
I think these might be existing DL1 subclasses, but it will be more than just DL1-6 (it is 3 / 6-7 cells) and I don't think it is really clear which they are. There are also 2 cells in another cluster (DL2?) targeted by the D'-Gal4 driver.
If this gets clarified in future it may be possible to add functionality (and synonyms) to the existing classes. For now, I think it might be best to use the parent class, rather than potentially annotate to the wrong neuron or add another subclass.
