### ISSUE TITLE
Remove recently added adult specificity to X lineage neuron terms [sf#8]

### ISSUE THREAD

**Issue by mmc46** [FlyBase/drosophila-anatomy-developmental-ontology#8]
**Reported by djs93 on 2013-06-11 14:07 UTC**
In the last update (1306), terms of the form X lineage neuron, defined as "neuron _that_ **develops_from** _some_ <neuroblast X\>" were given an additional restriction - to adult stages.  This was useful for the current VFB release, but in hindsight was a mistake.  As a result, a handfull of expression records for larval expression now have an officially adult specific term.  This should be fixed by broadening the meaning of these terms by removing the restriction to adult stage in both name and formal def. No retrofits will be required.

**Comment by mmc46** [comment]
**Commented by mmc46 on 2013-11-20 17:56 UTC**
Hi David,

Do you mean to remove only the 'intersection_of: part_of FBbt:00003624 ! adult brain' from all 'adult X lineage neuron' (and change the name)? 

And also remove the 'relationship: part_of FBbt:00050250 ! adult VPNp1 lineage clone'?

name: adult VPNp1 lineage neuron
def: "." [FlyBase:FBrf0221412, FlyBase:FBrf0221438]
subset: TL_lineage_clone
synonym: "adult BLD5 lineage neuron" EXACT [FlyBase:FBrf0217450]
synonym: "adult DC lineage neuron" EXACT [FlyBase:FBrf0211926]
xref: VFB:FBbt_00050251
intersection_of: FBbt:00005106 ! neuron
intersection_of: develops_from FBbt:00050249 ! neuroblast VPNp1
intersection_of: part_of FBbt:00003624 ! adult brain
relationship: part_of FBbt:00050250 ! adult VPNp1 lineage clone


And leave 'adult fruitless X neuron' as they are?

name: adult fruitless pIP-b neuron
def: "." [FlyBase:FBrf0211926, FlyBase:FBrf0221412, FlyBase:FBrf0221438]
xref: VFB:FBbt_00110481
intersection_of: FBbt:00005106 ! neuron
intersection_of: develops_from FBbt:00050249 ! neuroblast VPNp1
intersection_of: expresses FlyBase:FBgn0004652 ! fruitless
intersection_of: part_of FBbt:00110480 ! adult fruitless pIP-b lineage clone

**Comment by mmc46** [comment]
@dosumis Is this still to be corrected?

**Comment by Clare72** [comment]
Browsing results of `MATCH (a:Neuroblast)<-[develops_from]-(b) WHERE b:Neuron AND b:Class RETURN DISTINCT a.label, b.label`, it looks like most NBs now have a stage-neutral class (often in addition to adult-specific) for their neuronal progeny (but some don't).

Rather than removing all adult-specific terms, shall I just add new neutral terms where needed?

We probably do want to change `'part of' some 'adult brain'` to `'part of' some adult` for the adult-specific terms. This is also an issue for the adult-specific clones.

Also noticed that some terms are using non-matching NB terms e.g. 

neuroblast EBa1 | DALv2 lineage neuron
-- | --

so these neurons should probably be renamed too.

**Comment by Clare72** [comment]
brain requirement removed in #1120 (now nervous system)
name mismatches now seem to be fixed
closing this as it is too late to broaden definitions (most lineages now already have a stage non-specific term and original issue is from 8 years ago)
