### ISSUE TITLE
midline of ventral nerve cord

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#80]
There's a fairly frequent expression pattern usually described as "midline of the ventral nerve cord" or "ventral nerve cord midline". Could this term be added (either is fine), or alternatively, could both be added as synonyms to an existing FBbt term I'm failing to find in Vocabularies?

should be part_of ventral nerve cord (FBbt:00001102)

**Comment by nstaudt** [comment]
Do you refer to the embryonic or the adult nervous system? There is a term "ventral midline" (FBbt:00000093). Like "ventral nerve cord" it belongs to the embryonic/larval nervous system. But as far as I know there is no midline term for the adult term "thoracico-abdominal ganglion"...

**Comment by SianGramates** [comment]
I'm referring to the larval ventral nerve cord.  Now that I expand the part_of hierarchy, I see that ventral midline is part_of presumptive embryonic/larval nervous system (FBbt:00001055), which is defined as "the sum of all the structures in the embryo that will develop into the embryonic/larval nervous system"; that fits in with the definition of ventral midline, which is "the middle underside of the embryo". ventral midline is NOT part_of ventral nerve cord, nor even of "ventral nerve cord primordium". As defined, "ventral midline" is an embryonic-specific term.

What I'm looking for is a term that could be accurately used to describe the very common expression pattern of a line right down the center of the ventral nerve cord of a larva, including a third instar larva. I'm including an image of what I'm talking about from FBrf0180181.
![fbrf0180181_fig4](https://cloud.githubusercontent.com/assets/12848394/20066951/6668400a-a4e1-11e6-95fd-77f2ac4efe63.jpg)

**Comment by nstaudt** [comment]
I think there is no larval term for these cells. For example "ventral midline neuron" (FBbt:00005566) is per definition just embryonic and is not mentioned as part of the embryonic/larval nervous system. In addition, there are hardly any terms for the pupal nervous system.

**Comment by dosumis** [comment]
> ventral midline neuron" (FBbt:00005566) is per definition just embryonic

This is an error.  It should probably be part of the VNC, unless it includes neurons in the SOG/central brain, in which case it should be under embryonic/larval CNS.  A new term for VNC ventral midline neuron could be added. In either case the def could be fleshed out a bit.  I believe this refers to neurons that are born from midline neuroblasts and that are not members of a bilateral pair, but project symmetrically to both sides.

**Comment by SianGramates** [comment]
I'm referring to the larval ventral nerve cord.  Now that I expand the part_of hierarchy, I see that ventral midline is part_of presumptive embryonic/larval nervous system (FBbt:00001055), which is defined as "the sum of all the structures in the embryo that will develop into the embryonic/larval nervous system"; that fits in with the definition of ventral midline, which is "the middle underside of the embryo". ventral midline is NOT part_of ventral nerve cord, nor even of "ventral nerve cord primordium". As defined, "ventral midline" is an embryonic-specific term.

What I'm looking for is a term that could be accurately used to describe the very common expression pattern of a line right down the center of the ventral nerve cord of a larva, including a third instar larva. I'm including an image of what I'm talking about from FBrf0180181.

**Comment by SianGramates** [comment]
I think the terms may need to be elaborated.  I think it's important that we maintain a term specific to the underside of the embryo, as ventral midline is currently defined; that's a very common expression pattern. I generally dislike stage-specific terms, but in this case, it's important to be able to distinguish between a thin line on the bottom of a stage 5 embryo, the part of the developing ventral nerve where the midline neuroblasts and glioblasts are forming, and a line (not necessarily neurons or glia) down the middle of the larval ventral nerve cord.. All of those are things expression pattern curators need.

**Comment by mmc46** [comment]
The term ventral midline neuron" (FBbt:00005566) is not just embryonic. I'll correct the textual definition, but the term is both part of the embryo and larva CNS (as per existing relationships).

**Comment by mmc46** [comment]
@SianGramates From the example and from what I'm aware of, I guess you're looking for an anterior/posterior midline term. Is that right?

**Comment by SianGramates** [comment]
@mmc46 Yes, midline anterior to posterior. I really thing we need three terms: "ventral midline of embryo"; "ventral midline" (mapping onto current term, though I think the definition of the current term should be moved to "ventral midline of embryo"; maybe add some nervous system-specific language to definition); and "ventral midline of ventral nerve cord" (late embryonic-larval specific).

**Comment by mmc46** [comment]
The current terms 'ventral midline' and 'ventral midline neurons' cover both embryonic and larval, as they encompass where the neurons and glia form (as you mention in a previous comment). 
I thought the new term you wanted (from comments above) should describe things on the midline, embryonic and larval (and maybe adult), not necessarily ventral, just down the middle. Is that not the case?

**Comment by SianGramates** [comment]
@mmc46 Right; midline of ventral nerve cord, not ventral midline of ventral nerve cord. (though I think that pattern is indeed usually ventrally located).

**Comment by mmc46** [comment]
I've created stage specific midline terms 
embryonic midline FBbt:00111740
embryonic/larval midline FBbt:00111741
adult midline FBbt:00111742
(and there's a parent 'midline'. Children defined with intersection_of)

The current 'ventral midline' is a child of both 'embryonic/larval midline' and 'embryonic midline' (inferred)

**Comment by dosumis** [comment]
What's the classification?

**Comment by SianGramates** [comment]
I continue to think it would be a good idea if the term explicitly name-checked the ventral nerve cord. There's nothing neural-specific about the concept of a midline.

**Comment by mmc46** [comment]
Ok, I've changed the names.

**Comment by Clare72** [comment]
Thought I would have a go at fixing this - see connected pull request #863 for details

Summary:
 - all midlines changed to 'anatomical line' rather than 'multicellular structure'
 - 'ventral midline' no longer part of the nervous system (line seems like it should be the full length of the embryo)
 - renamed 'ventral midline' -> 'ventral midline of embryo' (developmental part of definition doesn't fit larva - removed larva from definition)
 - midline neurons now have_soma_location at the midline rather than being part_of the midline
 - merged 'ventral midline neuron' with 'midline neuron' as their definitions were referring to the same anatomy
 - renamed 'midline neuron' -> 'larval midline neuron' (to clarify that not adult)
 - renamed 'ventral neuron of the ventral midline' -> 'larval ventral midline neuron' (for clarity)
 - renamed 'medial neuron of the ventral midline' -> 'larval medial midline neuron' (for clarity)
 - renamed 'adult midline' -> 'adult midline of central nervous system' (to match definition)

**Comment by dosumis** [comment]
'Anatomical line' in FBbt appears to be lacking a definition, but it xrefs CARO CARO:0000008

http://www.ontobee.org/ontology/CARO?iri=http://purl.obolibrary.org/obo/CARO_0000008

Definition: A one dimensional, immaterial anatomical entity.
example of usage: A line between two points where these are typically used to measure some aspect of morphology, such as the distance between the eyes or the length of a leg.

So strictly, nuclei can't be part of this.  I think this was the original reason for making it a region.

**Comment by Clare72** [comment]
Yeah, I thought about just doing 'overlaps', but felt like that would be losing info.
It can't be 'multicellular structure' because the neuronal projections aren't really on the midline, but 'multi-cell-component structure' can't have whole cells and we might want to include whole neuroblasts.
What about 'midline' as an 'anatomical line' and specific (cell-containing) midlines as 'anatomical structure' that either 'overlaps' some 'midline' or 'has_part' some 'midline'?

**Comment by Clare72** [comment]
Updated summary:

 - 'midline' now an 'anatomical line' that the specific (cell containing) midlines overlap; specific midlines (except in embryo) are 'multi-cell-component-structure' rather than 'multicellular structure'
 - 'ventral midline' no longer part of the nervous system (seemed like it should be the full length of the embryo)
 - renamed 'ventral midline' -> 'ventral midline of embryo' (developmental part of definition doesn't fit larva - removed larva from definition)
 - midline neurons now have_soma_location at the midline rather than being part_of the midline (and develop_from midline neuroblasts)
 - midline neuroblasts are part_of an appropriate midline (depending on stage)
 - some reorganisation of midline neuroblasts - MP1 does not produce 'ventral' neurons, so not ventral (but still embryonic and VNC)
 - merged 'ventral midline neuron' with 'midline neuron' as their definitions were referring to the same anatomy
 - renamed 'midline neuron' -> 'larval midline neuron' (to clarify that not adult)
 - renamed 'ventral neuron of the ventral midline' -> 'larval ventral midline neuron' (for clarity)
 - renamed 'medial neuron of the ventral midline' -> 'larval medial midline neuron' (for clarity)
 - renamed 'adult midline' -> 'adult midline of central nervous system' (to match definition)
 - renamed 'ventral midline neuroblast' -> 'embryonic ventral midline neuroblast' as all children are only found in embryo and term was asserted to be part_of embryo
