### ISSUE TITLE
Please delete label on http://www.geneontology.org/formats/oboInOwl#hasDbXref

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#801]
label on  #hasDbXref is causing some pipeline issues for VFB.  Please could you remove before next release?  Doesn't  need a label as short_form is readable

**Comment by Clare72** [comment]
This is coming in from imports (GO, RO and PATO) rather than anything in fbbt-edit or in components, so would need to be stripped out post-release.
Is it sensible to remove this from fbbt.json? might other users not want the label there?
Could you remove it as part of the Jenkins job to update FBbt in VFB?

**Comment by dosumis** [comment]
OK.   Makes sense.  I guess there's no really good options for this apart from adding an  extra hack, given  the current pipeline.  We're  planning to  have  a curated list of properties in the V2  pipeline.

**Comment by dosumis** [comment]
The problem  is - people randomly attach labels to these things in source files - and never manage them through imports.

**Comment by Clare72** [comment]
Closing ticket - issue to be fixed elsewhere
