### ISSUE TITLE
FBrf0245463 Lee et al. 2020 Adult brain neuron types by lineage

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#813]
New paper from Tzumin Lee. https://elifesciences.org/articles/53518

We're currently ingesting images for this.

**Comment by dosumis** [comment]
Change  clone partonomy relationship to overlaps 'adult nervous system'

Include hemilineages - Schema TBC.

(Also double check  design pattern is followed)

**Comment by dosumis** [comment]
Schema for recording hemilineage:

I'd rather use a differentium.  Maybe make a quality for Notch on vs Notch off.  We could potentially axiomatise the quality more later.  Either that or use develops_from with some general cell class terms for notch on/off precursors.

For birth order -  Please use an annotation property to record, with value int. (a data property could also work - but important to test how it round-trips through OBO.

**Comment by Clare72** [comment]
How about ['Birth Order'](http://purl.obolibrary.org/obo/NCIT_C93517) from NCIT?

**Comment by Clare72** [comment]
>we have identified 467 morphological neuron types from 25 Vnd hemilineages in the fly central brain (Supplementary file 2)

Some of these are PAM neurons - mapped (in paper) to 14 existing (check synonyms) + 3 new to add. PAM neurons come from 2 lineages - do we want subclasses for each?
Some are AL neurons, not explicitly mapped in paper, but should be fairly easy to see which is which based on AL glomerulus and lineage (check synonyms and add hemilineage info), might be some new.
Some are CX neurons - almost certainly correspond to existing/soon to be published types, but may be more difficult to map, since we do not know lineages for all CX neurons.
Others would be difficult to map to existing types, so I guess this is where we need new classes - do we want to make type and/or group and/or hemilineage terms for each neuroblast?

Regarding birth order:
>The two-digit serial number starts from 01 and is assigned by arranging neuron types of the same hemilineage-topology class by first clustering neuron types based on closeness in morphology and then determining cluster sequence as well as intra-cluster neuron sequence to roughly reflect birth order

So birth order designation seems to be by type rather than by individual. Some lineages also have the same numerical designations for different topologies e.g. AOTUv1 has T01, H01 and P01 types.
Perhaps best not to add this as an integer right now (possible exception - first born neuron of a lineage is sometimes quite distinctive), but describe as early/late?

**Comment by dosumis** [comment]
We will add all 7 pairs of hemilineages in this  paper.  Pattern TBD.

Hold off on adding  individual classes, except where they clearly map to something  known until further correspondence with Tzumin.

(Related Data ready to load.)

**Comment by Clare72** [comment]
Issues for incorporation into FBbt:
 - Poor formatting of data in xlsx file: colour-coded information, merged cells, multiple sheets, special characters (see PAMs), inconsistent use of brackets for innervation patterns (sometimes subregions, sometimes a neuropil region, sometimes extent), 'extra information' requires manual review. This makes it difficult to automatically generate new terms.
 - Known types are not explicitly mapped and it is not clear which types are new. Even PAM neurons are not explicitly mapped to their types, there are three beta2 classes - are these all PAM04 (PAM-beta2), or subclasses, or new types innervating the same MB region?
 - Approximate birth order: types are NBLAST clusters, not single cells, so types could contain overlapping birth orders. This could also get messier if types are split/merged in future.
 - Not clear from spreadsheet which morphological types are born first - in FLAa2, are P01-08 born before or after H01-08 or are they mixed?

**Comment by Clare72** [comment]
Issues for incorporation into FBbt:
 - Poor formatting of data in xlsx file: colour-coded information, merged cells, multiple sheets, special characters (see PAMs), inconsistent use of brackets for innervation patterns (sometimes subregions, sometimes a neuropil region, sometimes extent), 'extra information' requires manual review. This makes it difficult to automatically generate new terms.
 - Known types are not explicitly mapped and it is not clear which types are new. Even PAM neurons are not explicitly mapped to their types, there are three beta2 classes - are these all PAM04 (PAM-beta2), or subclasses, or new types innervating the same MB region?
 - Approximate birth order: types are NBLAST clusters, not single cells, so types could contain overlapping birth orders. This could also get messier if types are split/merged in future.
 - Not clear from spreadsheet which morphological types are born first - in FLAa2, are P01-08 born before or after H01-08 or are they mixed?
