### ISSUE TITLE
AMMC VLP7 PN  - GABAergic?

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#88]
http://www.virtualflybrain.org/site/stacks/index.htm?id=FBbt_00110634

![image](https://cloud.githubusercontent.com/assets/112839/21638572/bf66b61e-d263-11e6-8b07-d76be3b7ac9e.png)

Given the exact synonym:

GABAergic aLN(GCI) [EXACT] (Vaughan et al., 2014)

Shouldn't this neuron be classified as GABAergic?

**Comment by dosumis** [comment]
BTW - where does the VLP7 name come from?  Can't find it two ref'd papers.

+ shouldn't this be a parent class: http://www.virtualflybrain.org/site/stacks/index.htm?id=FBbt_00111354 ?

**Comment by mmc46** [comment]
Named by me, because Clemens 2015 (http://dx.doi.org/10.1016/j.neuron.2015.08.014) describe some more AMMC-VLP neurons (see table 1), named up to 6 (AMMC-AV6 neuron, which actually corresponds to AMMC-A1.  Lai just names names AMMC-VLP, but they are a subtype, so I added the exact synonym. 
I can add a comment to the term, to make this explicit.   

On the GABAergic: Vaughan says there are 2 subsets of aLN(GCI) neurons: one they call canonical (that corresponds to AMMC-A1), and one they say is GABAergic (~15 neurons). It's the latter they match to the AMMC-VLP of Lai. I didn't think the evidence for GABA expression was strong enough, so I didn't add that. But I could add to the comment.

**Comment by mmc46** [comment]
Changes done.

**Comment by Clare72** [comment]
Looks like this is resolved - closing.
