### ISSUE TITLE
Add check for label & symbol uniqueness

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#948]
1. FBbt labels should be unique.  If not then fail build
2. labels overall - warn of duplicates, don't fail. 
3. symbols overall - fail for now.  consider making into warning later.

Robot now has built-in check: http://robot.obolibrary.org/report_queries/multiple_labels

SPARQL can be modified for FBbt & symbol checks.

**Comment by Clare72** [comment]
See http://robot.obolibrary.org/report

For duplicate labels there is the 'duplicate label' check - http://robot.obolibrary.org/report_queries/duplicate_label
It is currently set to WARN, rather than ERROR

From looking through fbbt.Makefile, we do 2 sets of qc - obo_qc_fbbt.owl and obo_qc_fbbt.obo, each producing a txt file. Both use the same qc profile, where duplicate_label check is set to WARN.
The obo check uses a file without the imports merged, while the owl check performs a merge without the `--collapse-import-closure false` option before doing the checks, so is checking a file with imports merged in.

To have different severity (ERROR/WARN) for duplicate labels in FBbt v FBbt+imports, I think we would need two qc profiles, one for the owl check and one for the obo check.

Duplicate symbol check can be added by modifying the duplicate_label query and adding to qc profile as detailed in http://robot.obolibrary.org/report 'Profiles' section

**Comment by dosumis** [comment]
> To have different severity (ERROR/WARN) for duplicate labels in FBbt v FBbt+imports, I think we would need two qc profiles, one for the owl check and one for the obo check.

I don't know off hand whether import status will make a difference, but give it a try.  The other way is just to write a custom SPARQL check with a FILTER clause that matches against fbbt purls.  See example here: https://api.triplydb.com/s/t1tdAoI2P

**Comment by Clare72** [comment]
It seems to make a difference - obo_qc_fbbt.owl.txt has several duplicate_label warnings:
>WARN	duplicate_label	FBbt:00005114	rdfs:label	synapse	
WARN	duplicate_label	GO:0045202	rdfs:label	synapse	
WARN	duplicate_label	CARO:0000007	rdfs:label	immaterial anatomical entity	
WARN	duplicate_label	FBbt:00007015	rdfs:label	immaterial anatomical entity	
WARN	duplicate_label	CARO:0000014	rdfs:label	cell part@en	
WARN	duplicate_label	GO:0044464	rdfs:label	cell part@en	
WARN	duplicate_label	FBbt:00007002	rdfs:label	cell	
WARN	duplicate_label	GO:0005623	rdfs:label	cell	
WARN	duplicate_label	FBbt:00005109	rdfs:label	axon	
WARN	duplicate_label	GO:0030424	rdfs:label	axon	

There are none in obo_qc_fbbt.obo.txt
